"""
Advice and rectify steps per sub-issue key — language-aware.
"""

_ADVICE = {
    "pt": {
        "scam_phishing": "Você pode ter interagido com um site falso criado para roubar suas credenciais ou esvaziar sua carteira. Esses sites imitam plataformas reais e podem capturar sua frase semente ou chave privada.",
        "scam_rugpull": "Um rug pull ocorre quando os desenvolvedores abandonam o projeto e fogem com os fundos. Se a liquidez foi removida subitamente ou a equipe desapareceu, isso provavelmente aconteceu.",
        "scam_romance": "Golpes românticos (pig butchering) envolvem construir confiança antes de convencer vítimas a investir em plataformas falsas. Esses golpistas geralmente fazem parte de grupos criminosos organizados.",
        "scam_impersonation": "Golpistas que se passam por suporte pedem sua frase semente ou acesso remoto. Suporte legítimo NUNCA fará isso.",
        "scam_pump": "Pump and dump inflam artificialmente o preço de um token antes que insiders vendam tudo, causando prejuízo a outros investidores.",
        "tx_stuck": "Sua transação aguarda processamento. Geralmente ocorre quando a taxa de gas foi definida muito baixa durante alta congestionamento.",
        "tx_failed": "Transação rejeitada pela blockchain — por gas insuficiente ou slippage. Seus fundos NÃO foram enviados.",
        "tx_wrong_address": "Transações em blockchain são irreversíveis. Recuperação é possível apenas se for um endereço de exchange conhecida.",
        "tx_missing": "Pode ser atraso de rede, confirmações pendentes, ou a plataforma exige mais confirmações de bloco.",
        "tx_double": "Pode ser bug de exibição, replay attack ou erro da plataforma. Verifique no explorador de blockchain.",
        "wallet_locked": "Seus fundos estão seguros na blockchain. Acesso pode ser restaurado com sua frase semente.",
        "wallet_hacked": "Se comprometida, um atacante pode ter sua chave privada. Aja imediatamente para mover fundos restantes para uma nova carteira.",
        "wallet_sync": "Problema de conexão entre o app e o nó blockchain. Seus fundos estão seguros — é apenas uma questão de exibição.",
        "wallet_seed": "Sem a frase semente, a recuperação é extremamente difícil. Consulte a documentação oficial da sua carteira.",
        "wallet_hw": "Seus fundos estão na blockchain — o dispositivo é apenas uma chave. Consulte o suporte oficial do fabricante.",
        "ex_withdrawal": "Saques atrasados por retenções de segurança, KYC, problemas de rede ou liquidez. Geralmente resolve em 24–72h.",
        "ex_frozen": "Contas congeladas por atividade suspeita, compliance AML ou exigências regulatórias.",
        "ex_kyc": "Problemas de KYC resolvem com documentação correta. Certifique-se de que o documento é válido e a selfie corresponde.",
        "ex_funds": "Pode ser atraso de exibição, erro de transferência ou depósito aguardando confirmações suficientes.",
        "ex_login": "Causado por falhas no 2FA, restrições de IP ou bloqueio de conta. Use o processo oficial de recuperação.",
        "ex_buy_pixel": "Problema com compra de Pixel para DePix registrado. Nossa equipe irá auxiliá-lo.",
        "ex_depix_lbtc": "Problema com troca de DePix por LBTC registrado. Nossa equipe irá auxiliá-lo.",
        "buy_pixel_issue": "Problema com sua compra de Pixel para DePix registrado. Nossa equipe irá investigar.",
        "buy_pixel_pending": "Seu pagamento pode ainda estar sendo processado. Confirmações podem levar alguns minutos.",
        "buy_pixel_wrong": "Discrepância no valor recebido registrada. Tenha os detalhes da transação prontos para o suporte.",
        "depix_lbtc_issue": "Problema com sua troca de DePix por LBTC registrado. Nossa equipe irá auxiliá-lo.",
        "depix_lbtc_rate": "Discrepância de taxa ou valor registrada. Nossa equipe irá revisar sua transação.",
        "depix_lbtc_stuck": "Sua troca pode ainda estar sendo processada. Se permanecer pendente por mais de 30 minutos, nossa equipe irá investigar.",
        "other": "Seu problema foi registrado. Revise os passos abaixo e entre em contato com o suporte se precisar de mais ajuda.",
    },
    "en": {
        "scam_phishing": "You may have interacted with a fake website designed to steal your credentials or drain your wallet. These sites mimic real platforms and can capture your seed phrase or private key.",
        "scam_rugpull": "A rug pull happens when developers abandon a project and run with investor funds. If liquidity was suddenly removed or the team disappeared, this is likely what occurred.",
        "scam_romance": "Romance/pig butchering scams involve building trust over time before convincing victims to invest on fake platforms. These scammers are often organized criminal groups.",
        "scam_impersonation": "Scammers posing as support agents often ask for your seed phrase or remote access. Legitimate support will NEVER ask for this.",
        "scam_pump": "Pump and dump schemes artificially inflate a token's price before insiders sell off, leaving other investors with losses.",
        "tx_stuck": "Your transaction is waiting to be processed. This usually happens when the gas fee was set too low during high network congestion.",
        "tx_failed": "A failed transaction was broadcast but rejected — often due to insufficient gas or slippage limits. Your funds were NOT sent.",
        "tx_wrong_address": "Blockchain transactions are irreversible. Recovery is only possible if it's a known exchange address and you act quickly.",
        "tx_missing": "Funds may be delayed due to network congestion, pending confirmations, or the receiving platform requiring more block confirmations.",
        "tx_double": "A duplicate transaction could be a display glitch, a replay attack, or a platform error. Check the blockchain explorer.",
        "wallet_locked": "Your funds are still safe on the blockchain. Access can be restored using your seed phrase.",
        "wallet_hacked": "If your wallet was compromised, an attacker may have your private key. Act immediately to move remaining funds to a new wallet.",
        "wallet_sync": "Sync issues are usually a connection problem between the wallet app and the blockchain node. Your funds are safe.",
        "wallet_seed": "Without your seed phrase, wallet recovery is extremely difficult. Check the wallet's official documentation for alternatives.",
        "wallet_hw": "Your funds remain on the blockchain — the device is just a key, not storage. Contact the manufacturer's official support.",
        "ex_withdrawal": "Withdrawal delays can be caused by security holds, KYC requirements, or network issues. Most resolve within 24–72 hours.",
        "ex_frozen": "Accounts are typically frozen due to suspicious activity detection, AML compliance checks, or regulatory requirements.",
        "ex_kyc": "KYC issues usually resolve with proper documentation. Ensure your ID is valid and your selfie matches the document.",
        "ex_funds": "Missing funds could be a display delay, an internal transfer error, or a deposit needing more block confirmations.",
        "ex_login": "Login issues are often caused by 2FA problems, IP restrictions, or account lockouts. Use the official recovery process.",
        "ex_buy_pixel": "Issue with buying Pixel to DePix recorded. Our support team will assist you with this transaction.",
        "ex_depix_lbtc": "Issue with exchanging DePix to LBTC recorded. Our support team will assist you with this transaction.",
        "buy_pixel_issue": "Problem with your Pixel to DePix purchase recorded. Our team will look into this for you.",
        "buy_pixel_pending": "Your payment may still be processing. Confirmations can take a few minutes depending on network congestion.",
        "buy_pixel_wrong": "A discrepancy in the received amount has been noted. Please keep your transaction details ready for support.",
        "depix_lbtc_issue": "Problem with your DePix to LBTC exchange recorded. Our team will assist you.",
        "depix_lbtc_rate": "Rate or amount discrepancy noted. Exchange rates may fluctuate — our team will review your transaction.",
        "depix_lbtc_stuck": "Your exchange may still be processing. If it remains pending after 30 minutes, our team will investigate.",
        "other": "Your issue has been logged. Review the steps below and contact support if you need further assistance.",
    },
    "es": {
        "scam_phishing": "Puede que hayas interactuado con un sitio falso diseñado para robar tus credenciales o vaciar tu billetera. Estos sitios imitan plataformas reales.",
        "scam_rugpull": "Un rug pull ocurre cuando los desarrolladores abandonan el proyecto y huyen con los fondos. Si la liquidez fue removida de repente, esto probablemente ocurrió.",
        "scam_romance": "Las estafas románticas implican construir confianza antes de convencer a las víctimas de invertir en plataformas falsas.",
        "scam_impersonation": "Los estafadores que se hacen pasar por soporte piden tu frase semilla o acceso remoto. El soporte legítimo NUNCA pedirá esto.",
        "scam_pump": "Los esquemas pump and dump inflan artificialmente el precio de un token antes de que los insiders vendan todo.",
        "tx_stuck": "Tu transacción está esperando ser procesada. Ocurre cuando la tarifa de gas fue muy baja durante alta congestión.",
        "tx_failed": "Transacción rechazada por la blockchain — por gas insuficiente o límites de slippage. Tus fondos NO fueron enviados.",
        "tx_wrong_address": "Las transacciones en blockchain son irreversibles. La recuperación solo es posible si es una dirección de exchange conocida.",
        "tx_missing": "Los fondos pueden estar retrasados por congestión de red o la plataforma requiere más confirmaciones de bloque.",
        "tx_double": "Podría ser un error de visualización, ataque de replay o error de la plataforma. Verifica en el explorador.",
        "wallet_locked": "Tus fondos están seguros en la blockchain. El acceso puede restaurarse con tu frase semilla.",
        "wallet_hacked": "Si fue comprometida, un atacante puede tener tu clave privada. Mueve los fondos restantes a una nueva billetera inmediatamente.",
        "wallet_sync": "Problema de conexión entre la app y el nodo blockchain. Tus fondos están seguros.",
        "wallet_seed": "Sin la frase semilla, la recuperación es extremadamente difícil. Consulta la documentación oficial.",
        "wallet_hw": "Tus fondos están en la blockchain — el dispositivo es solo una llave. Contacta el soporte oficial del fabricante.",
        "ex_withdrawal": "Los retrasos en retiros pueden deberse a retenciones de seguridad, KYC o problemas de red. Generalmente se resuelven en 24–72h.",
        "ex_frozen": "Las cuentas se congelan por actividad sospechosa, cumplimiento AML o requisitos regulatorios.",
        "ex_kyc": "Los problemas de KYC se resuelven con documentación correcta. Asegúrate de que el ID sea válido.",
        "ex_funds": "Pueden ser fondos en espera de confirmaciones, error de visualización o error de transferencia interna.",
        "ex_login": "Causado por problemas de 2FA, restricciones de IP o bloqueo de cuenta. Usa el proceso oficial de recuperación.",
        "ex_buy_pixel": "Problema con la compra de Pixel a DePix registrado. Nuestro equipo te asistirá.",
        "ex_depix_lbtc": "Problema con el intercambio de DePix a LBTC registrado. Nuestro equipo te asistirá.",
        "buy_pixel_issue": "Problema con tu compra de Pixel a DePix registrado. Nuestro equipo lo investigará.",
        "buy_pixel_pending": "Tu pago puede estar procesándose. Las confirmaciones pueden tardar unos minutos.",
        "buy_pixel_wrong": "Se registró una discrepancia en el monto recibido. Ten los detalles listos para el soporte.",
        "depix_lbtc_issue": "Problema con tu intercambio de DePix a LBTC registrado.",
        "depix_lbtc_rate": "Discrepancia de tasa o monto registrada. Nuestro equipo revisará tu transacción.",
        "depix_lbtc_stuck": "Tu intercambio puede estar procesándose. Si sigue pendiente tras 30 minutos, nuestro equipo investigará.",
        "other": "Tu problema ha sido registrado. Revisa los pasos y contacta soporte si necesitas más ayuda.",
    },
    "fr": {
        "scam_phishing": "Vous avez peut-être interagi avec un faux site conçu pour voler vos identifiants ou vider votre portefeuille.",
        "scam_rugpull": "Un rug pull se produit quand les développeurs abandonnent le projet avec les fonds. Si la liquidité a été retirée soudainement, c'est probablement ce qui s'est passé.",
        "scam_romance": "Les arnaques romantiques consistent à établir une confiance avant de convaincre les victimes d'investir sur de fausses plateformes.",
        "scam_impersonation": "Les escrocs se faisant passer pour le support demandent votre phrase de récupération ou un accès à distance. Le vrai support ne fera JAMAIS cela.",
        "scam_pump": "Les schémas pump and dump gonflent artificiellement le prix d'un token avant que les initiés vendent tout.",
        "tx_stuck": "Votre transaction attend d'être traitée. Cela se produit quand les frais de gas sont trop bas lors d'une forte congestion.",
        "tx_failed": "Transaction rejetée par la blockchain — gas insuffisant ou limites de slippage. Vos fonds n'ont PAS été envoyés.",
        "tx_wrong_address": "Les transactions blockchain sont irréversibles. La récupération n'est possible que si c'est une adresse d'exchange connue.",
        "tx_missing": "Les fonds peuvent être retardés par la congestion du réseau ou la plateforme requiert plus de confirmations.",
        "tx_double": "Cela peut être un bug d'affichage, une attaque de replay ou une erreur de plateforme. Vérifiez sur l'explorateur.",
        "wallet_locked": "Vos fonds sont en sécurité sur la blockchain. L'accès peut être restauré avec votre phrase de récupération.",
        "wallet_hacked": "Si compromis, un attaquant peut avoir votre clé privée. Déplacez immédiatement les fonds restants vers un nouveau portefeuille.",
        "wallet_sync": "Problème de connexion entre l'app et le nœud blockchain. Vos fonds sont en sécurité.",
        "wallet_seed": "Sans la phrase de récupération, la restauration est extrêmement difficile. Consultez la documentation officielle.",
        "wallet_hw": "Vos fonds sont sur la blockchain — l'appareil est juste une clé. Contactez le support officiel du fabricant.",
        "ex_withdrawal": "Les retards de retrait peuvent être causés par des vérifications de sécurité, KYC ou des problèmes de réseau.",
        "ex_frozen": "Les comptes sont gelés pour activité suspecte, conformité AML ou exigences réglementaires.",
        "ex_kyc": "Les problèmes KYC se résolvent avec une documentation correcte. Assurez-vous que l'ID est valide.",
        "ex_funds": "Cela peut être un délai d'affichage, une erreur de transfert ou un dépôt en attente de confirmations.",
        "ex_login": "Causé par des problèmes 2FA, des restrictions IP ou un verrouillage de compte. Utilisez la procédure officielle.",
        "ex_buy_pixel": "Problème d'achat de Pixel vers DePix enregistré. Notre équipe vous assistera.",
        "ex_depix_lbtc": "Problème d'échange DePix vers LBTC enregistré. Notre équipe vous assistera.",
        "buy_pixel_issue": "Problème avec votre achat Pixel vers DePix enregistré. Notre équipe l'examinera.",
        "buy_pixel_pending": "Votre paiement est peut-être encore en traitement. Les confirmations peuvent prendre quelques minutes.",
        "buy_pixel_wrong": "Une divergence de montant a été notée. Gardez vos détails de transaction pour le support.",
        "depix_lbtc_issue": "Problème avec votre échange DePix vers LBTC enregistré. Notre équipe vous assistera.",
        "depix_lbtc_rate": "Divergence de taux ou de montant notée. Notre équipe examinera votre transaction.",
        "depix_lbtc_stuck": "Votre échange est peut-être encore en cours. S'il reste en attente après 30 minutes, notre équipe enquêtera.",
        "other": "Votre problème a été enregistré. Consultez les étapes ci-dessous et contactez le support si nécessaire.",
    },
}

_RECTIFY = {
    "pt": {
        "scam_phishing": "CONNECT_WALLET",
        "scam_rugpull": "CONNECT_WALLET",
        "tx_stuck": "CONNECT_WALLET",
        "tx_failed": "CONNECT_WALLET",
        "wallet_locked": "CONNECT_WALLET",
        "wallet_hacked": "CONNECT_WALLET",
        "ex_withdrawal": "CONNECT_WALLET",
        "ex_frozen": "CONNECT_WALLET",
        "ex_buy_pixel": "CONNECT_WALLET",
        "ex_depix_lbtc": "CONNECT_WALLET",
        "other": "CONNECT_WALLET",
    },
    "en": {
        "scam_phishing": "CONNECT_WALLET",
        "scam_rugpull": "CONNECT_WALLET",
        "tx_stuck": "CONNECT_WALLET",
        "tx_failed": "CONNECT_WALLET",
        "wallet_locked": "CONNECT_WALLET",
        "wallet_hacked": "CONNECT_WALLET",
        "ex_withdrawal": "CONNECT_WALLET",
        "ex_frozen": "CONNECT_WALLET",
        "ex_buy_pixel": "CONNECT_WALLET",
        "ex_depix_lbtc": "CONNECT_WALLET",
        "other": "CONNECT_WALLET",
    },
    "es": {
        "scam_phishing": "CONNECT_WALLET",
        "scam_rugpull": "CONNECT_WALLET",
        "tx_stuck": "CONNECT_WALLET",
        "tx_failed": "CONNECT_WALLET",
        "wallet_locked": "CONNECT_WALLET",
        "wallet_hacked": "CONNECT_WALLET",
        "ex_withdrawal": "CONNECT_WALLET",
        "ex_frozen": "CONNECT_WALLET",
        "ex_buy_pixel": "CONNECT_WALLET",
        "ex_depix_lbtc": "CONNECT_WALLET",
        "other": "CONNECT_WALLET",
    },
    "fr": {
        "scam_phishing": "CONNECT_WALLET",
        "scam_rugpull": "CONNECT_WALLET",
        "tx_stuck": "CONNECT_WALLET",
        "tx_failed": "CONNECT_WALLET",
        "wallet_locked": "CONNECT_WALLET",
        "wallet_hacked": "CONNECT_WALLET",
        "ex_withdrawal": "CONNECT_WALLET",
        "ex_frozen": "CONNECT_WALLET",
        "ex_buy_pixel": "CONNECT_WALLET",
        "ex_depix_lbtc": "CONNECT_WALLET",
        "other": "CONNECT_WALLET",
    },
}


def get_advice(lang: str, sub_key: str) -> str:
    lang_advice = _ADVICE.get(lang, _ADVICE["en"])
    return lang_advice.get(sub_key, lang_advice.get("other", ""))


def get_rectify_steps(lang: str, sub_key: str) -> str:
    lang_rectify = _RECTIFY.get(lang, _RECTIFY["en"])
    return lang_rectify.get(sub_key, lang_rectify.get("other", ""))
